package natsauth

// Phase 3.5 surface — minting Account JWTs at runtime so ppz-server
// can provision per-org accounts on demand (OAuth signup, POST /orgs).
//
// Phase 3 had a single shared account whose JWT was generated by
// Pulumi at deploy time. Phase 3.5 needs the Operator key to be hot
// in the server process so new accounts can be signed without
// requiring a `pulumi up`.

import (
	"fmt"
	"time"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

// MintAccountJWT signs a fresh Account JWT for orgName, with the
// supplied signing-key public registered as an authorized signer.
// The Operator key (`operatorKP`) signs the JWT — caller is
// responsible for that key's security (production: env var).
//
// JetStream limits are set to unlimited (-1) — a single ppz-server
// is the only client of every account anyway, so per-account
// quotas don't add safety, only friction.
func MintAccountJWT(operatorKP nkeys.KeyPair, orgName string, accountKP, signingKP nkeys.KeyPair) (string, error) {
	accPub, err := accountKP.PublicKey()
	if err != nil {
		return "", fmt.Errorf("account pub: %w", err)
	}
	signPub, err := signingKP.PublicKey()
	if err != nil {
		return "", fmt.Errorf("signing pub: %w", err)
	}

	claims := jwt.NewAccountClaims(accPub)
	claims.Name = orgName
	claims.SigningKeys.Add(signPub)
	claims.Limits.JetStreamLimits.MemoryStorage = -1
	claims.Limits.JetStreamLimits.DiskStorage = -1
	claims.Limits.JetStreamLimits.Streams = -1
	claims.Limits.JetStreamLimits.Consumer = -1
	return claims.Encode(operatorKP)
}

// MintUserJWTInAccount mints a User JWT in the supplied account,
// signed by that account's signing key. Decoupled from `Account` so
// callers that hold (account_pub, signing_kp) directly — like
// per-org account loaders in Phase 3.5 — can mint without
// constructing an Account struct.
//
// expUnix is the JWT's `exp` claim (seconds since epoch). The
// `nbf` claim is set 30s before now to absorb clock skew.
func MintUserJWTInAccount(accountPub string, signingKP nkeys.KeyPair, name string, pubAllow, subAllow []string, expUnix int64) (jwtStr, seed string, err error) {
	userKP, err := nkeys.CreateUser()
	if err != nil {
		return "", "", fmt.Errorf("create user nkey: %w", err)
	}
	userPub, err := userKP.PublicKey()
	if err != nil {
		return "", "", fmt.Errorf("user pub: %w", err)
	}
	seedBytes, err := userKP.Seed()
	if err != nil {
		return "", "", fmt.Errorf("user seed: %w", err)
	}

	claims := jwt.NewUserClaims(userPub)
	claims.Name = name
	claims.IssuerAccount = accountPub
	claims.Pub.Allow = pubAllow
	claims.Sub.Allow = subAllow

	now := time.Now()
	claims.IssuedAt = now.Unix()
	claims.Expires = expUnix
	claims.NotBefore = now.Add(-30 * time.Second).Unix()

	encoded, err := claims.Encode(signingKP)
	if err != nil {
		return "", "", fmt.Errorf("encode user jwt: %w", err)
	}
	return encoded, string(seedBytes), nil
}
